version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build: ./devops-training
    ports:
      - "3000:3000"
    command: ["npm", "start"]
