name: PR Validation Workflow
on:
  push: # mudar para pull_request depois
    branches: [master]
jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
      - run: |
          cd devops-training
          npm install
          npm run build